config/routes.rb
Rails.application.routes.draw do
  resources :follows
  devise_for :users
  resources :tweets
  root "tweets#index"
  match ':controller(/:action(/:id))', :via => :get

end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :user
  belongs_to :follower, :class_name => "User"
  scope :find_followers, ->(user_id) { where(:user_id => user_id)}
  scope :find_following, ->(current_user_id) { where(:follower_id => current_user_id)}
  #scope :find_nonfollowers, ->(user_id) { where.not(user_id: [user_id])}
  #scope :find_nonfollowers, ->(user_id) { where(user_id: [user_id])}
end

app/models/follower.rb
class Follower < ActiveRecord::Base
  belongs_to :user, class_name: "User", foreign_key: "User_id"
end

app/models/follower_tweet.rb
class FollowerTweet < ActiveRecord::Base
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  scope :find_follower_tweets, ->(followers_ids) {where(user_id: [followers_ids])}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tweets
  has_many :follows
  has_many :followers, :through => :follows
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :set_follow, only: [:show, :edit, :update, :destroy]

  # GET /follows
  # GET /follows.json
  def index
    @follows = Follow.all
    @myFollowers = Follow.find_followers(current_user.id)
    #@myNonFollowers = Follow.find_nonfollowers(current_user.id)

  end

  # GET /follows/1
  # GET /follows/1.json
  def show
  end

  # GET /follows/new
  def new
    @follow = current_user.follows.build
  end

  def listNonFollowers
    @myFollowers = Follow.find_followers(current_user.id)
    allUsers = User.all
    allUsers_id = []
    followers_id = []
    
    for user in allUsers
      allUsers_id.push(user.id)
    end
      
    for follower in @myFollowers
      followers_id.push(follower.follower_id)
    end
    
    non_followers_id = (allUsers_id - followers_id - [current_user.id])
    @allUsers = []
    
    for non_follower in non_followers_id
      @allUsers.push(User.find(non_follower))
    end
  end

  def find_my_following
    @myFollowing = Follow.find_following(current_user.id)
  end

  # GET /follows/1/edit
  def edit
  end

  # POST /follows
  # POST /follows.json

  def create
    @follow = current_user.follows.build(:follower_id => params[:follower_id])
    if @follow.save
      flash[:notice] = "Added a follower."
      redirect_to follows_url
    else
      flash[:notice] = "Failed to save"
      redirect_to root_path
    end
  end



  # PATCH/PUT /follows/1
  # PATCH/PUT /follows/1.json
  def update
    respond_to do |format|
      if @follow.update(follow_params)
        format.html { redirect_to @follow, notice: 'Follow was successfully updated.' }
        format.json { render :show, status: :ok, location: @follow }
      else
        format.html { render :edit }
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /follows/1
  # DELETE /follows/1.json
  def destroy
    @follow.destroy
    respond_to do |format|
      format.html { redirect_to follows_url, notice: 'Follower was removed' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_follow
      @follow = Follow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def follow_params
      params.require(:follow).permit(:user_id, :follower_id)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:index, :show]
  before_action :authorized_user, only: [:edit, :update, :destroy]
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.build
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = current_user.tweets.build(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def authorized_user
    @tweet = current_user.tweets.find_by(id: params[:id])
    redirect_to tweets_path, notice: "Not authorized to edit this link" if @tweet.nil?
  end

  def followed_tweets
    @follower_rows = Follow.find_followers(current_user.id)
    @follower_ids = []

    for follower in @follower_rows
      @follower_ids.push(follower.follower_id)
    end
    @follower_ids = @follower_ids.push(current_user.id)
    @followed_tweets = Tweet.find_follower_tweets(@follower_ids)

  end

  def latest_tweets
    @rows = Follow.find_followers(current_user.id)
    @follower_ids = []

    for follower in @rows
      @follower_ids.push(follower.follower_id)
    end
    @fs = ''
    for x in @follower_ids
      @fs.concat(x.to_s)
      @fs.concat(',')
    end
    @fs = @fs[0,@fs.length - 1]
    @latest_tweets = Tweet.find_by_sql "select created_at,message,user_id from (
select created_at,message,user_id, row_number() over (
partition by user_id order by created_at DESC ) as row_rank from tweets ) as ranked where row_rank < 3 and user_id in (#{@fs})"
   
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/followers/index.html.haml
='This is the followers page for id = '
= @id

app/views/follows/_form.html.haml
= form_for @follow do |f|
  - if @follow.errors.any?
    #error_explanation
      %h2= "#{pluralize(@follow.errors.count, "error")} prohibited this follow from being saved:"
      %ul
        - @follow.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.hidden_field :user_id, value:current_user.id
  .field
    = f.label :follower_id
    = f.number_field :follower_id
  .actions
    = f.submit 'Save'

app/views/follows/edit.html.haml
%h1 Editing follow

= render 'form'

= link_to 'Show', @follow
\|
= link_to 'Back', follows_path

app/views/follows/find_my_following.html.haml
%h1 You are followed by: 
%table
  %tbody
    - @myFollowing.each do |element|
      %tr
        %td= User.find(element.user_id).name
        %td= " | "
        %td= User.find(element.user_id).email

app/views/follows/index.html.haml
%h1 You currently follow: 

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @myFollowers.each do |myFollower|
      %tr
        %td= User.find(myFollower.follower_id).name
        %td= link_to 'Remove', myFollower, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

<!-- = link_to 'Add New Follower', new_follow_path -->
= link_to 'Want to follow new users?', :controller => :follows, :action => :listNonFollowers, :id =>current_user.id 
= link_to 'Users who follow me', :controller => :follows, :action => :find_my_following, :id =>current_user.id

app/views/follows/listNonFollowers.html.haml
%h1 Whom do you want to follow ? 
%table
  %tbody
    - @allUsers.each do |non_follower|
      %tr
        %td= non_follower.name
        %td= link_to 'Follow', follows_path(:follower_id => non_follower.id),:method => :post 

app/views/follows/new.html.haml
%h1 New follow

= render 'form'
<!--render 'userList'-->

= link_to 'Back', follows_path

app/views/follows/show.html.haml
%p#notice= notice

%p
  %b User:
  = @follow.user_id
%p
  %b Follower:
  = @follow.follower_id

= link_to 'Edit', edit_follow_path(@follow)
\|
= link_to 'Back', follows_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
  <% end %>
<% if user_signed_in? %>
  <ul>
    <li><%= link_to 'Home', tweets_path %></li>
    <li><%= link_to 'Submit Tweet', new_tweet_path %></li>
    <li><%= link_to 'Account', edit_user_registration_path %></li>
    <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
  </ul>
<% else %>
  <ul>
    <li><%= link_to 'Sign up', new_user_registration_path %></li>
    <li><%= link_to 'Sign in', new_user_session_path %></li>
  </ul>
<% end %>
<%= yield %>

</body>
</html>

app/views/tweets/_form.html.haml
= form_for @tweet do |f|
  - if @tweet.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tweet.errors.count, "error")} prohibited this tweet from being saved:"
      %ul
        - @tweet.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :message
    = f.text_field :message
  .actions
    = f.submit 'Save'

app/views/tweets/edit.html.haml
%h1 Editing tweet

= render 'form'

= link_to 'Show', @tweet
\|
= link_to 'Back', tweets_path

app/views/tweets/followed_tweets.html.haml
%h1 Listing follower's tweets
%table
  %thead
    %tr
      %th Message
      %th
      %th
      %th

  %tbody
    -@followed_tweets.each do |followed_tweet|
      %tr
        %td= followed_tweet.message
        %td=  "|"
        %td= User.find(followed_tweet.user_id).name
        -if followed_tweet.user == current_user
          %td= link_to 'Edit', edit_tweet_path(followed_tweet)
          %td= link_to 'Destroy', followed_tweet, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'Home', root_path

app/views/tweets/index.html.haml
%h1 Listing tweets
%table
  %thead
    %tr
      %th Message
      %th
      %th
      %th

  %tbody
    - @tweets.each do |tweet|
      %tr
        %td= tweet.message
        %td= "|"
        %td= User.find(tweet.user_id).name
        %td= link_to 'Show', tweet
         
        - if tweet.user == current_user
          %td= link_to 'Edit', edit_tweet_path(tweet)
          %td= link_to 'Destroy', tweet, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Tweet', new_tweet_path
= " | "
<!-- = link_to 'Add followers' , :controller => :followers, :action => :findFollowers, :id => current_user.id -->
-if current_user != nil
  =link_to 'List my followers' , follows_path 
  = " | " 
  =link_to 'Followers Tweets', :controller => :tweets, :action => :followed_tweets, :id => current_user.id
  = " | "
  =link_to 'Latest tweets by followers', :controller => :tweets, :action => :latest_tweets, :id => current_user.id

app/views/tweets/latest_tweets.html.haml
%h1 Listing follower's latest tweets
%table
  %thead
    %tr
      %th Message
      %th
      %th
      %th

  %tbody
    -@latest_tweets.each do |latest_tweet|
      %tr
        %td= latest_tweet.message
        %td= "|"
        %td= User.find(latest_tweet.user_id).name
%br

= link_to 'Home', root_path

app/views/tweets/new.html.haml
%h1 New tweet

= render 'form'

= link_to 'Back', tweets_path

app/views/tweets/show.html.haml
%p#notice= notice

%p
  %b Message:
  = @tweet.message

= link_to 'Edit', edit_tweet_path(@tweet)
\|
= link_to 'Back', tweets_path